using System.Collections.Generic;

namespace Flow.Launcher.Plugin.Http_Status_Codes
{
    public static class HttpStatusCodes
    {
        public static readonly Dictionary<int, (string Description, string Link)> Codes = new Dictionary<int, (string, string)>
        {
            { 100, ("100 - Continue", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100") },
            { 101, ("101 - Switching Protocols", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/101") },
            { 102, ("102 - Processing", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/102") },
            { 103, ("103 - Early Hints", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103") },
            { 200, ("200 - OK", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200") },
            { 201, ("201 - Created", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201") },
            { 202, ("202 - Accepted", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202") },
            { 203, ("203 - Non-Authoritative Information", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/203") },
            { 204, ("204 - No Content", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204") },
            { 205, ("205 - Reset Content", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/205") },
            { 206, ("206 - Partial Content", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206") },
            { 207, ("207 - Multi-Status", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/207") },
            { 208, ("208 - Already Reported", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/208") },
            { 226, ("226 - IM Used", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/226") },
            { 300, ("300 - Multiple Choices", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/300") },
            { 301, ("301 - Moved Permanently", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301") },
            { 302, ("302 - Found", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302") },
            { 303, ("303 - See Other", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303") },
            { 304, ("304 - Not Modified", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304") },
            { 305, ("305 - Use Proxy", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#305_use_proxy") },
            { 306, ("306 - unused", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#306_unused") },
            { 307, ("307 - Temporary Redirect", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307") },
            { 308, ("308 - Permanent Redirect", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308") },
            { 400, ("400 - Bad Request", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400") },
            { 401, ("401 - Unauthorized", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401") },
            { 402, ("402 - Payment Required", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402") },
            { 403, ("403 - Forbidden", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403") },
            { 404, ("404 - Not Found", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404") },
            { 405, ("405 - Method Not Allowed", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405") },
            { 406, ("406 - Not Acceptable", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406") },
            { 407, ("407 - Proxy Authentication Required", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407") },
            { 408, ("408 - Request Timeout", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408") },
            { 409, ("409 - Conflict", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409") },
            { 410, ("410 - Gone", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410") },
            { 411, ("411 - Length Required", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/411") },
            { 412, ("412 - Precondition Failed", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412") },
            { 413, ("413 - Payload Too Large", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413") },
            { 414, ("414 - URI Too Long", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414") },
            { 415, ("415 - Unsupported Media Type", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415") },
            { 416, ("416 - Range Not Satisfiable", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/416") },
            { 417, ("417 - Expectation Failed", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/417") },
            { 418, ("418 - I'm a teapot", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418") },
            { 421, ("421 - Misdirected Request", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/421") },
            { 422, ("422 - Unprocessable Entity", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422") },
            { 423, ("423 - Locked", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/423") },
            { 424, ("424 - Failed Dependency", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/424") },
            { 425, ("425 - Too Early", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/425") },
            { 426, ("426 - Upgrade Required", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426") },
            { 428, ("428 - Precondition Required", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/428") },
            { 429, ("429 - Too Many Requests", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429") },
            { 431, ("431 - Request Header Fields Too Large", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431") },
            { 451, ("451 - Unavailable For Legal Reasons", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/451") },
            { 500, ("500 - Internal Server Error", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500") },
            { 501, ("501 - Not Implemented", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501") },
            { 502, ("502 - Bad Gateway", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502") },
            { 503, ("503 - Service Unavailable", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503") },
            { 504, ("504 - Gateway Timeout", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504") },
            { 505, ("505 - HTTP Version Not Supported", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/505") },
            { 506, ("506 - Variant Also Negotiates", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/506") },
            { 507, ("507 - Insufficient Storage", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/507") },
            { 508, ("508 - Loop Detected", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/508") },
            { 510, ("510 - Not Extended", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/510") },
            { 511, ("511 - Network Authentication Required", "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/511") }
        };
    }
}